
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.iata.cargo.Vocabulary;


/**
 * Booking details
 * 
 * This class was generated by OWL2Java 0.17.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_BookingOption)
public class BookingOption
    extends LogisticsObject
    implements Serializable
{

    /**
     * Booking Segment of the Booking Option
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingSegment)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingSegment bookingSegment;
    /**
     * booking times details of the Booking Option (proposed or actual)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingTimes)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingTimes bookingTimes;
    /**
     * Carrier details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_carrier_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Company carrier;
    /**
     * Reference to the Carrier products included in the offer
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_carrierProductInfo_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CarrierProduct carrierProductInfo;
    /**
     * Consignee details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_consignee_A)
    protected Set<Company> consignee;
    /**
     * Freight forwarder details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_freightForwarder_A)
    protected Set<Company> freightForwarder;
    /**
     * Other parties to be notified of the booking evolution
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_notifyParty_A)
    protected Set<Company> notifyParty;
    /**
     * Parties involved in the Booking Option (e.g. shipper, forwarder, ...)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_parties)
    protected Set<Party> parties;
    /**
     * Price of the Booking (if different from the offer)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_price_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Price price;
    /**
     * Reference to the Booking option request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_requestRef_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingOptionRequest requestRef;
    /**
     * Routing details of the offer, to be compared with routing preferences of the quote request
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_routing_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Routing routing;
    /**
     * Schedule details of the Booking Option (proposed or actual)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_schedule)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Schedule schedule;
    /**
     * Details of the shipement that is to be shipped
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipmentDetails_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Shipment shipmentDetails;
    /**
     * Shipper details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipper_A)
    protected Set<Company> shipper;
    /**
     * Transport segment linked to the offer, including the Departure and Arrival locations
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportMovement_A)
    protected Set<TransportSegment> transportMovement;
    /**
     * House or Master Waybill unique identifier
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_waybillNumber_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Waybill waybillNumber;
    /**
     * Status of the Booking with regards to the step in the Sales and Booking process: Quoted, Booked (to be confirmed)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_bookingStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String bookingStatus;
    /**
     * Starting datetime of availability of the booking option
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_offerValidFrom)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected Date offerValidFrom;
    /**
     * Ending datetime of availability of the booking option
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_offerValidTo)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected Date offerValidTo;
    /**
     * Indicates if the offer is a perfect match to the quote request (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_requestMatchInd)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean requestMatchInd;
    /**
     * Indicate the secruty state of the shipment, screened or not
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_shipmentSecurityStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String shipmentSecurityStatus;

    public void setBookingSegment(BookingSegment bookingSegment) {
        this.bookingSegment = bookingSegment;
    }

    public BookingSegment getBookingSegment() {
        return bookingSegment;
    }

    public void setBookingTimes(BookingTimes bookingTimes) {
        this.bookingTimes = bookingTimes;
    }

    public BookingTimes getBookingTimes() {
        return bookingTimes;
    }

    public void setCarrier(Company carrier) {
        this.carrier = carrier;
    }

    public Company getCarrier() {
        return carrier;
    }

    public void setCarrierProductInfo(CarrierProduct carrierProductInfo) {
        this.carrierProductInfo = carrierProductInfo;
    }

    public CarrierProduct getCarrierProductInfo() {
        return carrierProductInfo;
    }

    public void setConsignee(Set<Company> consignee) {
        this.consignee = consignee;
    }

    public Set<Company> getConsignee() {
        return consignee;
    }

    public void setFreightForwarder(Set<Company> freightForwarder) {
        this.freightForwarder = freightForwarder;
    }

    public Set<Company> getFreightForwarder() {
        return freightForwarder;
    }

    public void setNotifyParty(Set<Company> notifyParty) {
        this.notifyParty = notifyParty;
    }

    public Set<Company> getNotifyParty() {
        return notifyParty;
    }

    public void setParties(Set<Party> parties) {
        this.parties = parties;
    }

    public Set<Party> getParties() {
        return parties;
    }

    public void setPrice(Price price) {
        this.price = price;
    }

    public Price getPrice() {
        return price;
    }

    public void setRequestRef(BookingOptionRequest requestRef) {
        this.requestRef = requestRef;
    }

    public BookingOptionRequest getRequestRef() {
        return requestRef;
    }

    public void setRouting(Routing routing) {
        this.routing = routing;
    }

    public Routing getRouting() {
        return routing;
    }

    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }

    public Schedule getSchedule() {
        return schedule;
    }

    public void setShipmentDetails(Shipment shipmentDetails) {
        this.shipmentDetails = shipmentDetails;
    }

    public Shipment getShipmentDetails() {
        return shipmentDetails;
    }

    public void setShipper(Set<Company> shipper) {
        this.shipper = shipper;
    }

    public Set<Company> getShipper() {
        return shipper;
    }

    public void setTransportMovement(Set<TransportSegment> transportMovement) {
        this.transportMovement = transportMovement;
    }

    public Set<TransportSegment> getTransportMovement() {
        return transportMovement;
    }

    public void setWaybillNumber(Waybill waybillNumber) {
        this.waybillNumber = waybillNumber;
    }

    public Waybill getWaybillNumber() {
        return waybillNumber;
    }

    public void setBookingStatus(String bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    public String getBookingStatus() {
        return bookingStatus;
    }

    public void setOfferValidFrom(Date offerValidFrom) {
        this.offerValidFrom = offerValidFrom;
    }

    public Date getOfferValidFrom() {
        return offerValidFrom;
    }

    public void setOfferValidTo(Date offerValidTo) {
        this.offerValidTo = offerValidTo;
    }

    public Date getOfferValidTo() {
        return offerValidTo;
    }

    public void setRequestMatchInd(Boolean requestMatchInd) {
        this.requestMatchInd = requestMatchInd;
    }

    public Boolean getRequestMatchInd() {
        return requestMatchInd;
    }

    public void setShipmentSecurityStatus(String shipmentSecurityStatus) {
        this.shipmentSecurityStatus = shipmentSecurityStatus;
    }

    public String getShipmentSecurityStatus() {
        return shipmentSecurityStatus;
    }

}
