
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Company details
 * 
 * This class was generated by OWL2Java 0.14.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Company)
public class Company
    implements Serializable
{

    @Id(generated = true)
@JsonProperty("@id")
    protected String id;
    @JsonIgnore
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @JsonIgnore
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
@JsonProperty("@type")
    protected Set<String> types;
    @Properties
    @JsonIgnore
    protected Map<String, Set<String>> properties;
    /**
     * Company branches
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_branch)
    protected Set<Branch> branch;
    /**
     * IATA two-character airline code 
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_airlineCode)
    protected Set<String> airlineCode;
    /**
     * IATA three-numeric airline prefix number 
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_airlinePrefix)
    protected Set<String> airlinePrefix;
    /**
     * IATA accredited cargo agent 7 digit number
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_iATACargoAgentCode)
    protected Set<String> iATACargoAgentCode;
    /**
     * Name of company or organization
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_name)
    protected Set<String> name1;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Company {"+ name)+"<")+ id)+">")+"}");
    }

    public void setBranch(Set<Branch> branch) {
        this.branch = branch;
    }

    public Set<Branch> getBranch() {
        return branch;
    }

    public void setAirlineCode(Set<String> airlineCode) {
        this.airlineCode = airlineCode;
    }

    public Set<String> getAirlineCode() {
        return airlineCode;
    }

    public void setAirlinePrefix(Set<String> airlinePrefix) {
        this.airlinePrefix = airlinePrefix;
    }

    public Set<String> getAirlinePrefix() {
        return airlinePrefix;
    }

    public void setIATACargoAgentCode(Set<String> iATACargoAgentCode) {
        this.iATACargoAgentCode = iATACargoAgentCode;
    }

    public Set<String> getIATACargoAgentCode() {
        return iATACargoAgentCode;
    }

    public void setName1(Set<String> name1) {
        this.name1 = name1;
    }

    public Set<String> getName1() {
        return name1;
    }

}
