
package org.iata.cargo.model;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.iata.cargo.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Signature details of the Epermit for Live Animals
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_EpermitSignature)
public class EpermitSignature
    extends LogisticsObject
    implements Serializable
{

    /**
     * Reference to the LiveAnimalsEpermit this Signature applies to
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_appliesToEpermit)
@JsonProperty(Vocabulary.s_p_appliesToEpermit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_LiveAnimalsEpermit, max = 1)
    })
    protected Set<Thing> appliesToEpermit;
    /**
     * Signatory company name
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasSignatoryCompany)
@JsonProperty(Vocabulary.s_p_hasSignatoryCompany)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Company, max = 1)
    })
    protected Company hasSignatoryCompany;
    /**
     * Security Stamp ID
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSecurityStampIdentifier)
@JsonProperty(Vocabulary.s_p_hasSecurityStampIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasSecurityStampIdentifier;
    /**
     * Role of the signatory with regards to the ePermit: Applicant, Permit issuer, Issuing Authority or Examining authority
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSignatoryRole)
@JsonProperty(Vocabulary.s_p_hasSignatoryRole)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasSignatoryRole;
    /**
     * Date and time of the signature
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSignatureDate)
@JsonProperty(Vocabulary.s_p_hasSignatureDate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime hasSignatureDate;
    /**
     * Signatory signature authentication text
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSignatureStatement)
@JsonProperty(Vocabulary.s_p_hasSignatureStatement)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasSignatureStatement;
    /**
     * Code specifying a type of government action such as inspection, detention, fumigation, security.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSignatureTypeCode)
@JsonProperty(Vocabulary.s_p_hasSignatureTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasSignatureTypeCode;

    public void setAppliesToEpermit(Set<Thing> appliesToEpermit) {
        this.appliesToEpermit = appliesToEpermit;
    }

    public Set<Thing> getAppliesToEpermit() {
        return appliesToEpermit;
    }

    public void setHasSignatoryCompany(Company hasSignatoryCompany) {
        this.hasSignatoryCompany = hasSignatoryCompany;
    }

    public Company getHasSignatoryCompany() {
        return hasSignatoryCompany;
    }

    public void setHasSecurityStampIdentifier(Set<String> hasSecurityStampIdentifier) {
        this.hasSecurityStampIdentifier = hasSecurityStampIdentifier;
    }

    public Set<String> getHasSecurityStampIdentifier() {
        return hasSecurityStampIdentifier;
    }

    public void setHasSignatoryRole(Set<String> hasSignatoryRole) {
        this.hasSignatoryRole = hasSignatoryRole;
    }

    public Set<String> getHasSignatoryRole() {
        return hasSignatoryRole;
    }

    public void setHasSignatureDate(OffsetDateTime hasSignatureDate) {
        this.hasSignatureDate = hasSignatureDate;
    }

    public OffsetDateTime getHasSignatureDate() {
        return hasSignatureDate;
    }

    public void setHasSignatureStatement(String hasSignatureStatement) {
        this.hasSignatureStatement = hasSignatureStatement;
    }

    public String getHasSignatureStatement() {
        return hasSignatureStatement;
    }

    public void setHasSignatureTypeCode(Set<String> hasSignatureTypeCode) {
        this.hasSignatureTypeCode = hasSignatureTypeCode;
    }

    public Set<String> getHasSignatureTypeCode() {
        return hasSignatureTypeCode;
    }

}
