
package org.iata.cargo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.iata.cargo.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Superclass: LogisticsAgents describe acting entities in the logistics supply chain such as persons and organizations
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsAgent)
public class LogisticsAgent
    extends LogisticsObject
    implements Serializable
{


}
