
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.*;
import io.swagger.v3.oas.annotations.media.Schema;
import org.iata.api.model.AccessDelegationRequest;
import org.iata.api.model.ChangeRequest;
import org.iata.api.model.SubscriptionRequest;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Logistics Object parent class, containing all common properties for logistics objects.
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsObject)
@Schema(
        type = "object",
        title = "LogisticsObject"
)
public class LogisticsObject
    implements Serializable
{

    @Id(generated = true)
    @JsonProperty("@id")
    protected String id;
    @Types
    @JsonProperty("@type")
    protected Set<String> types;
    /**
     * References to the CheckActions performed on the object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checks)
    @JsonProperty(Vocabulary.s_p_checks)
    protected Set<Check> checks;
    /**
     * Events object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_events)
    @JsonProperty(Vocabulary.s_p_events)
    protected Set<LogisticsEvent> events;
    /**
     * References to all associated ExternalReferences
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_externalReferences)
    @JsonProperty(Vocabulary.s_p_externalReferences)
    protected Set<ExternalReference> externalReferences;
    /**
     * Company identifier from the Internet of Logistics of the entity that hosts the object.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_companyIdentifier)
    @JsonProperty(Vocabulary.s_p_companyIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String companyIdentifier;
    /**
     * Indicator whether a logistics object is a skeleton object
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_skeletonIndicator)
    @JsonProperty(Vocabulary.s_p_skeletonIndicator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean skeletonIndicator;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }


    public void setChecks(Set<Check> checks) {
        this.checks = checks;
    }

    public Set<Check> getChecks() {
        return checks;
    }

    public void setEvents(Set<LogisticsEvent> events) {
        this.events = events;
    }

    public Set<LogisticsEvent> getEvents() {
        return events;
    }

    public void setExternalReferences(Set<ExternalReference> externalReferences) {
        this.externalReferences = externalReferences;
    }

    public Set<ExternalReference> getExternalReferences() {
        return externalReferences;
    }

    public void setCompanyIdentifier(String companyIdentifier) {
        this.companyIdentifier = companyIdentifier;
    }

    public String getCompanyIdentifier() {
        return companyIdentifier;
    }

    public void setSkeletonIndicator(Boolean skeletonIndicator) {
        this.skeletonIndicator = skeletonIndicator;
    }

    public Boolean getSkeletonIndicator() {
        return skeletonIndicator;
    }

}
