
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.iata.cargo.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Superclass: LogisticsActivity is a scheduled set of tasks that is executed as part of one or more Services
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsActivity)
public class LogisticsActivity
    extends LogisticsObject
    implements Serializable
{

    /**
     * References to CheckActions performed for the Activity
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasCheckActions)
@JsonProperty(Vocabulary.s_p_hasCheckActions)
    protected Set<Check> hasCheckActions;
    /**
     * Information about contacts
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasContactDetail)
@JsonProperty(Vocabulary.s_p_hasContactDetail)
    protected Set<ContactDetail> hasContactDetail;
    /**
     * References to Actors (Person, NonHumanActor) acting as contacts
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasContactPerson)
@JsonProperty(Vocabulary.s_p_hasContactPerson)
    protected Set<Actor> hasContactPerson;
    /**
     * Reference to Services this Activity is executed for
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_isPartOfService)
@JsonProperty(Vocabulary.s_p_isPartOfService)
    protected Set<LogisticsService> isPartOfService;
    /**
     * Enum stating the status of the Activity
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasExecutionStatus)
@JsonProperty(Vocabulary.s_p_hasExecutionStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasExecutionStatus;

    public void setHasCheckActions(Set<Check> hasCheckActions) {
        this.hasCheckActions = hasCheckActions;
    }

    public Set<Check> getHasCheckActions() {
        return hasCheckActions;
    }

    public void setHasContactDetail(Set<ContactDetail> hasContactDetail) {
        this.hasContactDetail = hasContactDetail;
    }

    public Set<ContactDetail> getHasContactDetail() {
        return hasContactDetail;
    }

    public void setHasContactPerson(Set<Actor> hasContactPerson) {
        this.hasContactPerson = hasContactPerson;
    }

    public Set<Actor> getHasContactPerson() {
        return hasContactPerson;
    }

    public void setIsPartOfService(Set<LogisticsService> isPartOfService) {
        this.isPartOfService = isPartOfService;
    }

    public Set<LogisticsService> getIsPartOfService() {
        return isPartOfService;
    }

    public void setHasExecutionStatus(Set<String> hasExecutionStatus) {
        this.hasExecutionStatus = hasExecutionStatus;
    }

    public Set<String> getHasExecutionStatus() {
        return hasExecutionStatus;
    }

}
