
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import org.iata.cargo.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Refers to a Company and its role in a specific context, e.g Company A as shipper. Cargo-XML Code List 1.15 can be used as a reference with the addition of "Notify Party"
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Party)
public class Party
    implements Serializable
{

    @Id(generated = true)
@JsonProperty("@id")
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
@JsonIgnore
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
@JsonIgnore
    protected String description;
    @Types
@JsonProperty("@type")
    protected Set<String> types;
    @Properties
@JsonIgnore
    protected Map<String, Set<String>> properties;
    /**
     * Reference to the Organization acting in the role of this Party
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_describesRoleOfOrganization)
@JsonProperty(Vocabulary.s_p_describesRoleOfOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Organization, max = 1)
    })
    protected Set<Thing> describesRoleOfOrganization;
    /**
     * Reference to the Company
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasOrganization)
@JsonProperty(Vocabulary.s_p_hasOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Company, max = 1)
    })
    protected Set<Thing> hasOrganization;
    @OWLObjectProperty(iri = Vocabulary.s_p_hasOtherIdentifier)
@JsonProperty(Vocabulary.s_p_hasOtherIdentifier)
    protected Set<OtherIdentifier> hasOtherIdentifier;
    /**
     * Role fo the Company in the context. Can refer to Code List 1.36 in the CXML Toolkit
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasRole)
@JsonProperty(Vocabulary.s_p_hasRole)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasRole;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Party {"+ name)+"<")+ id)+">")+"}");
    }

    public void setDescribesRoleOfOrganization(Set<Thing> describesRoleOfOrganization) {
        this.describesRoleOfOrganization = describesRoleOfOrganization;
    }

    public Set<Thing> getDescribesRoleOfOrganization() {
        return describesRoleOfOrganization;
    }

    public void setHasOrganization(Set<Thing> hasOrganization) {
        this.hasOrganization = hasOrganization;
    }

    public Set<Thing> getHasOrganization() {
        return hasOrganization;
    }

    public void setHasOtherIdentifier(Set<OtherIdentifier> hasOtherIdentifier) {
        this.hasOtherIdentifier = hasOtherIdentifier;
    }

    public Set<OtherIdentifier> getHasOtherIdentifier() {
        return hasOtherIdentifier;
    }

    public void setHasRole(Set<String> hasRole) {
        this.hasRole = hasRole;
    }

    public Set<String> getHasRole() {
        return hasRole;
    }

}
