
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Superclass: PhysicalLogisticObjects represent the digital twin of an object in the logistics suppy chain that physically exist
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PhysicalLogisticsObject)
@Schema(
        type = "object",
        title = "PhysicalLogisticsObject",
        allOf = {
                LogisticsObject.class
        }
)
public class PhysicalLogisticsObject
    extends LogisticsObject
    implements Serializable
{

    /**
     * References to all connected IotDevices
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_attachedIotDevices)
    @JsonProperty(Vocabulary.s_p_attachedIotDevices)
    protected Set<IotDevice> attachedIotDevices;
    /**
     * References to the Actions the object is involved in
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_involvedInActions)
    @JsonProperty(Vocabulary.s_p_involvedInActions)
    protected Set<LogisticsAction> involvedInActions;

    public void setAttachedIotDevices(Set<IotDevice> attachedIotDevices) {
        this.attachedIotDevices = attachedIotDevices;
    }

    public Set<IotDevice> getAttachedIotDevices() {
        return attachedIotDevices;
    }

    public void setInvolvedInActions(Set<LogisticsAction> involvedInActions) {
        this.involvedInActions = involvedInActions;
    }

    public Set<LogisticsAction> getInvolvedInActions() {
        return involvedInActions;
    }

}
