
package org.iata.cargo.model;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.iata.cargo.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * LiveAnimals subclass of Piece
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PieceLiveAnimals)
public class PieceLiveAnimals
    extends Piece
    implements Serializable
{

    /**
     * Reference to the permits associated with the Live Animals
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasAssociatedEpermit)
@JsonProperty(Vocabulary.s_p_hasAssociatedEpermit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_EpermitConsignment, max = 1)
    })
    protected Set<Thing> hasAssociatedEpermit;
    /**
     * Country of last re-export (box 12a)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasExportTradeCountry)
@JsonProperty(Vocabulary.s_p_hasExportTradeCountry)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Country, max = 1)
    })
    protected Set<Thing> hasExportTradeCountry;
    /**
     * country of origin (box 12)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasOriginTradeCountry)
@JsonProperty(Vocabulary.s_p_hasOriginTradeCountry)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Country, max = 1)
    })
    protected Country hasOriginTradeCountry;
    /**
     * Defined in Resolution Conf. 13.6 and is required for pre-Convention specimens (box 12b)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasAcquisitionDateTime)
@JsonProperty(Vocabulary.s_p_hasAcquisitionDateTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime hasAcquisitionDateTime;
    /**
     * total number of specimens exported in the current calendar year and the current annuela quota for the species concerned (box 11a)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasAnnualQuotaQuantity)
@JsonProperty(Vocabulary.s_p_hasAnnualQuotaQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasAnnualQuotaQuantity;
    /**
     * Operations code ID. Refers to the number of the registered captive-breeding or artifical propagation operation (box 12b)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasCategoryCode)
@JsonProperty(Vocabulary.s_p_hasCategoryCode)
    protected Set<String> hasCategoryCode;
    /**
     * Appendix number of the convention (I, II or III) (box 10)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasGoodsTypeCode)
@JsonProperty(Vocabulary.s_p_hasGoodsTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasGoodsTypeCode;
    /**
     * Appendix number of the convention (I, II or III) (box 10)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasGoodsTypeExtensionCode)
@JsonProperty(Vocabulary.s_p_hasGoodsTypeExtensionCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasGoodsTypeExtensionCode;
    /**
     * Issuing date for Origin reference permit or re-export reference Certificate (box 12)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasOriginReferencePermitDateTime)
@JsonProperty(Vocabulary.s_p_hasOriginReferencePermitDateTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime hasOriginReferencePermitDateTime;
    /**
     * identifier of Origin reference permit or re-export reference Certificate (box 12/12a)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasOriginReferencePermitIdentifier)
@JsonProperty(Vocabulary.s_p_hasOriginReferencePermitIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasOriginReferencePermitIdentifier;
    /**
     * Document type code of origin reference permit or re-export reference Certificate (box 12/12a)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasOriginReferencePermitTypeCode)
@JsonProperty(Vocabulary.s_p_hasOriginReferencePermitTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasOriginReferencePermitTypeCode;
    /**
     * Quantity including units (box 11)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasQuantityAnimals)
@JsonProperty(Vocabulary.s_p_hasQuantityAnimals)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer hasQuantityAnimals;
    /**
     * Species common name (box 8)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSpeciesCommonName)
@JsonProperty(Vocabulary.s_p_hasSpeciesCommonName)
    protected Set<String> hasSpeciesCommonName;
    /**
     * Species scientific name (box 7)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSpeciesScientificName)
@JsonProperty(Vocabulary.s_p_hasSpeciesScientificName)
    protected Set<String> hasSpeciesScientificName;
    /**
     * Description of specimens, including age and sex if LA (box 9)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSpecimenDescription)
@JsonProperty(Vocabulary.s_p_hasSpecimenDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasSpecimenDescription;
    /**
     * Description of specimens, CITES type code (box 9)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSpecimenTypeCode)
@JsonProperty(Vocabulary.s_p_hasSpecimenTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasSpecimenTypeCode;

    public void setHasAssociatedEpermit(Set<Thing> hasAssociatedEpermit) {
        this.hasAssociatedEpermit = hasAssociatedEpermit;
    }

    public Set<Thing> getHasAssociatedEpermit() {
        return hasAssociatedEpermit;
    }

    public void setHasExportTradeCountry(Set<Thing> hasExportTradeCountry) {
        this.hasExportTradeCountry = hasExportTradeCountry;
    }

    public Set<Thing> getHasExportTradeCountry() {
        return hasExportTradeCountry;
    }

    public void setHasOriginTradeCountry(Country hasOriginTradeCountry) {
        this.hasOriginTradeCountry = hasOriginTradeCountry;
    }

    public Country getHasOriginTradeCountry() {
        return hasOriginTradeCountry;
    }

    public void setHasAcquisitionDateTime(OffsetDateTime hasAcquisitionDateTime) {
        this.hasAcquisitionDateTime = hasAcquisitionDateTime;
    }

    public OffsetDateTime getHasAcquisitionDateTime() {
        return hasAcquisitionDateTime;
    }

    public void setHasAnnualQuotaQuantity(Set<String> hasAnnualQuotaQuantity) {
        this.hasAnnualQuotaQuantity = hasAnnualQuotaQuantity;
    }

    public Set<String> getHasAnnualQuotaQuantity() {
        return hasAnnualQuotaQuantity;
    }

    public void setHasCategoryCode(Set<String> hasCategoryCode) {
        this.hasCategoryCode = hasCategoryCode;
    }

    public Set<String> getHasCategoryCode() {
        return hasCategoryCode;
    }

    public void setHasGoodsTypeCode(Set<String> hasGoodsTypeCode) {
        this.hasGoodsTypeCode = hasGoodsTypeCode;
    }

    public Set<String> getHasGoodsTypeCode() {
        return hasGoodsTypeCode;
    }

    public void setHasGoodsTypeExtensionCode(Set<String> hasGoodsTypeExtensionCode) {
        this.hasGoodsTypeExtensionCode = hasGoodsTypeExtensionCode;
    }

    public Set<String> getHasGoodsTypeExtensionCode() {
        return hasGoodsTypeExtensionCode;
    }

    public void setHasOriginReferencePermitDateTime(OffsetDateTime hasOriginReferencePermitDateTime) {
        this.hasOriginReferencePermitDateTime = hasOriginReferencePermitDateTime;
    }

    public OffsetDateTime getHasOriginReferencePermitDateTime() {
        return hasOriginReferencePermitDateTime;
    }

    public void setHasOriginReferencePermitIdentifier(Set<String> hasOriginReferencePermitIdentifier) {
        this.hasOriginReferencePermitIdentifier = hasOriginReferencePermitIdentifier;
    }

    public Set<String> getHasOriginReferencePermitIdentifier() {
        return hasOriginReferencePermitIdentifier;
    }

    public void setHasOriginReferencePermitTypeCode(String hasOriginReferencePermitTypeCode) {
        this.hasOriginReferencePermitTypeCode = hasOriginReferencePermitTypeCode;
    }

    public String getHasOriginReferencePermitTypeCode() {
        return hasOriginReferencePermitTypeCode;
    }

    public void setHasQuantityAnimals(Integer hasQuantityAnimals) {
        this.hasQuantityAnimals = hasQuantityAnimals;
    }

    public Integer getHasQuantityAnimals() {
        return hasQuantityAnimals;
    }

    public void setHasSpeciesCommonName(Set<String> hasSpeciesCommonName) {
        this.hasSpeciesCommonName = hasSpeciesCommonName;
    }

    public Set<String> getHasSpeciesCommonName() {
        return hasSpeciesCommonName;
    }

    public void setHasSpeciesScientificName(Set<String> hasSpeciesScientificName) {
        this.hasSpeciesScientificName = hasSpeciesScientificName;
    }

    public Set<String> getHasSpeciesScientificName() {
        return hasSpeciesScientificName;
    }

    public void setHasSpecimenDescription(String hasSpecimenDescription) {
        this.hasSpecimenDescription = hasSpecimenDescription;
    }

    public String getHasSpecimenDescription() {
        return hasSpecimenDescription;
    }

    public void setHasSpecimenTypeCode(String hasSpecimenTypeCode) {
        this.hasSpecimenTypeCode = hasSpecimenTypeCode;
    }

    public String getHasSpecimenTypeCode() {
        return hasSpecimenTypeCode;
    }

}
