
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Map;
import java.util.Set;


/**
 * Individual piece or virtual grouping of pieces
 * 
 * This class was generated by OWL2Java 0.14.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Piece)
public class Piece
    implements Serializable
{

    @Id(generated = true)
@JsonProperty("@id")
    protected String id;
    @JsonIgnore
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @JsonIgnore
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
@JsonProperty("@type")
    protected Set<String> types;
    @Properties
    @JsonIgnore
    protected Map<String, Set<String>> properties;
    /**
     * Details of contained piece(s)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_containedPiece)
    protected Set<Piece> containedPiece;
    /**
     * Customs details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_customsInfo)
    protected Set<CustomsInfo> customsInfo;
    /**
     * Dimensions details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_dimensions_A)
    protected Set<Dimensions> dimensions;
    /**
     * Event details e.g. DEP, ARR, FOH, RCS, security screening, etc
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_event_A_A)
    protected Set<Event> event;
    /**
     * Reference documents details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_externalReference)
    protected Set<ExternalReference> externalReference;
    /**
     * Weight details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_grossWeight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, min = 1, max = -1)
    })
    protected Set<Value> grossWeight;
    /**
     * Other piece identification ( e.g. Shipping Marks, Seal)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherIdentifier_A_A)
    protected Set<OtherIdentifier> otherIdentifier;
    /**
     * Other party company details - e.g. the party to be notified
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherParty)
    protected Set<Company> otherParty;
    /**
     * Packaging details 
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_packagingType)
    protected Set<PackagingType> packagingType;
    /**
     * Product of the piece, mandatory when there are no items
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_product_A)
    protected Set<Product> product;
    /**
     * Goods production country, mandatory when there are no Items
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_productionCountry_A)
    protected Set<Country> productionCountry;
    /**
     * Security details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_securityStatus)
    protected Set<SecurityStatus> securityStatus;
    /**
     * Security requests
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_serviceRequest_A)
    protected Set<ServiceRequest> serviceRequest;
    /**
     * Shipper company details - e.g. the party shipping the piece
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_shipper_A)
    protected Set<Company> shipper;
    /**
     * Special Handling details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_specialHandling_A)
    protected Set<SpecialHandling> specialHandling;
    /**
     * Segment related to the transport status
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportSegment)
    protected Set<TransportSegment> transportSegment;
    /**
     * ULD on which the (virtual) piece has been loaded into - URIs of the ULD
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldReference)
    protected Set<Uld> uldReference;
    /**
     * Volumetric weight details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_volumetricWeight)
    protected Set<VolumetricWeight> volumetricWeight;
    /**
     * Ad hoc security statement required by state regulators
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_additionalSecurityInfo)
    protected Set<String> additionalSecurityInfo;
    /**
     * Coload indicator for the pieces (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_coload)
    protected Set<Boolean> coload;
    /**
     * General goods description
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_goodsDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", min = 1, max = -1)
    })
    protected Set<String> goodsDescription;
    /**
     * Specify how the piece will be delivered (bulk or ULD)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_loadType)
    protected Set<String> loadType;
    /**
     * Shipper's Load And Count  ( total contained piece count as provided by shipper)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_slac)
    protected Set<BigDecimal> slac;
    /**
     * Stackable indicator for the pieces (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_stackable)
    protected Set<Boolean> stackable;
    /**
     * Turnable indicator for the pieces (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_turnable)
    protected Set<Boolean> turnable;
    /**
     * Unique Piece Identifier (UPID) of the piece. Refer IATA Recommended Practice 1689
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_upid_A)
    protected Set<String> upid;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Piece {"+ name)+"<")+ id)+">")+"}");
    }

    public void setContainedPiece(Set<Piece> containedPiece) {
        this.containedPiece = containedPiece;
    }

    public Set<Piece> getContainedPiece() {
        return containedPiece;
    }

    public void setCustomsInfo(Set<CustomsInfo> customsInfo) {
        this.customsInfo = customsInfo;
    }

    public Set<CustomsInfo> getCustomsInfo() {
        return customsInfo;
    }

    public void setDimensions(Set<Dimensions> dimensions) {
        this.dimensions = dimensions;
    }

    public Set<Dimensions> getDimensions() {
        return dimensions;
    }

    public void setEvent(Set<Event> event) {
        this.event = event;
    }

    public Set<Event> getEvent() {
        return event;
    }

    public void setExternalReference(Set<ExternalReference> externalReference) {
        this.externalReference = externalReference;
    }

    public Set<ExternalReference> getExternalReference() {
        return externalReference;
    }

    public void setGrossWeight(Set<Value> grossWeight) {
        this.grossWeight = grossWeight;
    }

    public Set<Value> getGrossWeight() {
        return grossWeight;
    }

    public void setOtherIdentifier(Set<OtherIdentifier> otherIdentifier) {
        this.otherIdentifier = otherIdentifier;
    }

    public Set<OtherIdentifier> getOtherIdentifier() {
        return otherIdentifier;
    }

    public void setOtherParty(Set<Company> otherParty) {
        this.otherParty = otherParty;
    }

    public Set<Company> getOtherParty() {
        return otherParty;
    }

    public void setPackagingType(Set<PackagingType> packagingType) {
        this.packagingType = packagingType;
    }

    public Set<PackagingType> getPackagingType() {
        return packagingType;
    }

    public void setProduct(Set<Product> product) {
        this.product = product;
    }

    public Set<Product> getProduct() {
        return product;
    }

    public void setProductionCountry(Set<Country> productionCountry) {
        this.productionCountry = productionCountry;
    }

    public Set<Country> getProductionCountry() {
        return productionCountry;
    }

    public void setSecurityStatus(Set<SecurityStatus> securityStatus) {
        this.securityStatus = securityStatus;
    }

    public Set<SecurityStatus> getSecurityStatus() {
        return securityStatus;
    }

    public void setServiceRequest(Set<ServiceRequest> serviceRequest) {
        this.serviceRequest = serviceRequest;
    }

    public Set<ServiceRequest> getServiceRequest() {
        return serviceRequest;
    }

    public void setShipper(Set<Company> shipper) {
        this.shipper = shipper;
    }

    public Set<Company> getShipper() {
        return shipper;
    }

    public void setSpecialHandling(Set<SpecialHandling> specialHandling) {
        this.specialHandling = specialHandling;
    }

    public Set<SpecialHandling> getSpecialHandling() {
        return specialHandling;
    }

    public void setTransportSegment(Set<TransportSegment> transportSegment) {
        this.transportSegment = transportSegment;
    }

    public Set<TransportSegment> getTransportSegment() {
        return transportSegment;
    }

    public void setUldReference(Set<Uld> uldReference) {
        this.uldReference = uldReference;
    }

    public Set<Uld> getUldReference() {
        return uldReference;
    }

    public void setVolumetricWeight(Set<VolumetricWeight> volumetricWeight) {
        this.volumetricWeight = volumetricWeight;
    }

    public Set<VolumetricWeight> getVolumetricWeight() {
        return volumetricWeight;
    }

    public void setAdditionalSecurityInfo(Set<String> additionalSecurityInfo) {
        this.additionalSecurityInfo = additionalSecurityInfo;
    }

    public Set<String> getAdditionalSecurityInfo() {
        return additionalSecurityInfo;
    }

    public void setCoload(Set<Boolean> coload) {
        this.coload = coload;
    }

    public Set<Boolean> getCoload() {
        return coload;
    }

    public void setGoodsDescription(Set<String> goodsDescription) {
        this.goodsDescription = goodsDescription;
    }

    public Set<String> getGoodsDescription() {
        return goodsDescription;
    }

    public void setLoadType(Set<String> loadType) {
        this.loadType = loadType;
    }

    public Set<String> getLoadType() {
        return loadType;
    }

    public void setSlac(Set<BigDecimal> slac) {
        this.slac = slac;
    }

    public Set<BigDecimal> getSlac() {
        return slac;
    }

    public void setStackable(Set<Boolean> stackable) {
        this.stackable = stackable;
    }

    public Set<Boolean> getStackable() {
        return stackable;
    }

    public void setTurnable(Set<Boolean> turnable) {
        this.turnable = turnable;
    }

    public Set<Boolean> getTurnable() {
        return turnable;
    }

    public void setUpid(Set<String> upid) {
        this.upid = upid;
    }

    public Set<String> getUpid() {
        return upid;
    }

}
