
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.*;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Product details
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Product)
public class Product
    extends LogisticsObject
    implements Serializable
{

    /**
     * Reference to the pieces where the product can be found. This needs to be filled in case there is no Item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_descriptionForContentOfPieces)
    @JsonProperty(Vocabulary.s_p_descriptionForContentOfPieces)
    protected Set<Piece> descriptionForContentOfPieces;
    /**
     * Reference to the Items in which the product can be found.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_descriptionForItems)
    @JsonProperty(Vocabulary.s_p_descriptionForItems)
    protected Set<Item> descriptionForItems;
    /**
     * Manufacturing company details and contacts
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_manufacturer)
    @JsonProperty(Vocabulary.s_p_manufacturer)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Company manufacturer;
    /**
     * Charateristics of the product
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherCharacteristics)
    @JsonProperty(Vocabulary.s_p_otherCharacteristics)
    protected Set<Characteristic> otherCharacteristics;
    /**
     * Details about any other identifier, depending on the context of use
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherIdentifiers)
    @JsonProperty(Vocabulary.s_p_otherIdentifiers)
    protected Set<OtherIdentifier> otherIdentifiers;
    /**
     * Indicates the specific commodity on which the rate class code is applied
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_commodityItemNumber)
    @JsonProperty(Vocabulary.s_p_commodityItemNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String commodityItemNumber;
    /**
     * Natural language description if required
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_description)
    @JsonProperty(Vocabulary.s_p_description)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String description;
    /**
     * Harmonized Commodity code, refer to hsType used. 6 minimum digits are expected.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsCode)
    @JsonProperty(Vocabulary.s_p_hsCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsCode;
    /**
     * Commodity description
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsCommodityDescription)
    @JsonProperty(Vocabulary.s_p_hsCommodityDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsCommodityDescription;
    /**
     * If no Code provided, name of commodity
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsCommodityName)
    @JsonProperty(Vocabulary.s_p_hsCommodityName)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsCommodityName;
    /**
     * Reference identifying the type of standard code to be used for the Commodity Classification (Brussels Tariff Nomenclature, EU Harmonized System Code, UN Standard International Trade Classification). Mandatory if the commodity code is more than 6 digits
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsType)
    @JsonProperty(Vocabulary.s_p_hsType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsType;
    /**
     * Manufacturer's unique product identifier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_uniqueIdentifier)
    @JsonProperty(Vocabulary.s_p_uniqueIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String uniqueIdentifier;

    public void setDescriptionForContentOfPieces(Set<Piece> descriptionForContentOfPieces) {
        this.descriptionForContentOfPieces = descriptionForContentOfPieces;
    }

    public Set<Piece> getDescriptionForContentOfPieces() {
        return descriptionForContentOfPieces;
    }

    public void setDescriptionForItems(Set<Item> descriptionForItems) {
        this.descriptionForItems = descriptionForItems;
    }

    public Set<Item> getDescriptionForItems() {
        return descriptionForItems;
    }

    public void setManufacturer(Company manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Company getManufacturer() {
        return manufacturer;
    }

    public void setOtherCharacteristics(Set<Characteristic> otherCharacteristics) {
        this.otherCharacteristics = otherCharacteristics;
    }

    public Set<Characteristic> getOtherCharacteristics() {
        return otherCharacteristics;
    }

    public void setOtherIdentifiers(Set<OtherIdentifier> otherIdentifiers) {
        this.otherIdentifiers = otherIdentifiers;
    }

    public Set<OtherIdentifier> getOtherIdentifiers() {
        return otherIdentifiers;
    }

    public void setCommodityItemNumber(String commodityItemNumber) {
        this.commodityItemNumber = commodityItemNumber;
    }

    public String getCommodityItemNumber() {
        return commodityItemNumber;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setHsCode(String hsCode) {
        this.hsCode = hsCode;
    }

    public String getHsCode() {
        return hsCode;
    }

    public void setHsCommodityDescription(String hsCommodityDescription) {
        this.hsCommodityDescription = hsCommodityDescription;
    }

    public String getHsCommodityDescription() {
        return hsCommodityDescription;
    }

    public void setHsCommodityName(String hsCommodityName) {
        this.hsCommodityName = hsCommodityName;
    }

    public String getHsCommodityName() {
        return hsCommodityName;
    }

    public void setHsType(String hsType) {
        this.hsType = hsType;
    }

    public String getHsType() {
        return hsType;
    }

    public void setUniqueIdentifier(String uniqueIdentifier) {
        this.uniqueIdentifier = uniqueIdentifier;
    }

    public String getUniqueIdentifier() {
        return uniqueIdentifier;
    }

}
