
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.*;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Ratings details
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Ratings)
public class Ratings
    extends LogisticsObject
    implements Serializable
{

    /**
     * Reference to the Prices based on this Ratings
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forPrices)
    @JsonProperty(Vocabulary.s_p_forPrices)
    protected Set<Price> forPrices;
    /**
     * Reference to the BookingOptionRequests
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_preferenceOfRequests)
    @JsonProperty(Vocabulary.s_p_preferenceOfRequests)
    protected Set<BookingOptionRequest> preferenceOfRequests;
    /**
     * Reference to the ranges
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ranges)
    @JsonProperty(Vocabulary.s_p_ranges)
    protected Set<Ranges> ranges;
    /**
     * Subtotal of the charge
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_billingChargeIdentifier)
    @JsonProperty(Vocabulary.s_p_billingChargeIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double billingChargeIdentifier;
    /**
     * Charge code, refer to CargoXML Code List 1.1
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_chargeCode)
    @JsonProperty(Vocabulary.s_p_chargeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String chargeCode;
    /**
     * Description of the charge e.g. Airfreight, fuel, etc.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_chargeDescription)
    @JsonProperty(Vocabulary.s_p_chargeDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String chargeDescription;
    /**
     * Indicates if charge is prepaid or collect (P, C)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_chargePaymentType)
    @JsonProperty(Vocabulary.s_p_chargePaymentType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String chargePaymentType;
    /**
     * Type of charge that should match the code expressed in either chargeCode, otherChargeCode or billingChargeIndentifier data properties.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_chargeType)
    @JsonProperty(Vocabulary.s_p_chargeType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String chargeType;
    /**
     * Entitlement code to define if charges are Due carrier (C) or Due agent (A). Refer to CXML Code List 1.3
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_entitlement)
    @JsonProperty(Vocabulary.s_p_entitlement)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String entitlement;
    /**
     * Refer to CargoXML Code List 1.2 for Other Charges
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_otherChargeCode)
    @JsonProperty(Vocabulary.s_p_otherChargeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String otherChargeCode;
    /**
     * Specification of the price e.g. Street, Group, Spot, etc.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_priceSpecification)
    @JsonProperty(Vocabulary.s_p_priceSpecification)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String priceSpecification;
    /**
     * Reference of price specifications
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_priceSpecificationRef)
    @JsonProperty(Vocabulary.s_p_priceSpecificationRef)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String priceSpecificationRef;
    /**
     * Used if there is an applicable quantity to the rate (Usually a Time or a Number)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_rateQuantity)
    @JsonProperty(Vocabulary.s_p_rateQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String rateQuantity;
    /**
     * Used to identify if the Ratings are Face, Published or Actual ratings. Expected values are F, A, C.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_ratingsType)
    @JsonProperty(Vocabulary.s_p_ratingsType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String ratingsType;
    /**
     * IATA 3-letter code of the rate combination point
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_rcp)
    @JsonProperty(Vocabulary.s_p_rcp)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String rcp;
    /**
     * Subtotal of the charge
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_subTotal)
    @JsonProperty(Vocabulary.s_p_subTotal)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double subTotal;

    public void setForPrices(Set<Price> forPrices) {
        this.forPrices = forPrices;
    }

    public Set<Price> getForPrices() {
        return forPrices;
    }

    public void setPreferenceOfRequests(Set<BookingOptionRequest> preferenceOfRequests) {
        this.preferenceOfRequests = preferenceOfRequests;
    }

    public Set<BookingOptionRequest> getPreferenceOfRequests() {
        return preferenceOfRequests;
    }

    public void setRanges(Set<Ranges> ranges) {
        this.ranges = ranges;
    }

    public Set<Ranges> getRanges() {
        return ranges;
    }

    public void setBillingChargeIdentifier(Double billingChargeIdentifier) {
        this.billingChargeIdentifier = billingChargeIdentifier;
    }

    public Double getBillingChargeIdentifier() {
        return billingChargeIdentifier;
    }

    public void setChargeCode(String chargeCode) {
        this.chargeCode = chargeCode;
    }

    public String getChargeCode() {
        return chargeCode;
    }

    public void setChargeDescription(String chargeDescription) {
        this.chargeDescription = chargeDescription;
    }

    public String getChargeDescription() {
        return chargeDescription;
    }

    public void setChargePaymentType(String chargePaymentType) {
        this.chargePaymentType = chargePaymentType;
    }

    public String getChargePaymentType() {
        return chargePaymentType;
    }

    public void setChargeType(String chargeType) {
        this.chargeType = chargeType;
    }

    public String getChargeType() {
        return chargeType;
    }

    public void setEntitlement(String entitlement) {
        this.entitlement = entitlement;
    }

    public String getEntitlement() {
        return entitlement;
    }

    public void setOtherChargeCode(String otherChargeCode) {
        this.otherChargeCode = otherChargeCode;
    }

    public String getOtherChargeCode() {
        return otherChargeCode;
    }

    public void setPriceSpecification(String priceSpecification) {
        this.priceSpecification = priceSpecification;
    }

    public String getPriceSpecification() {
        return priceSpecification;
    }

    public void setPriceSpecificationRef(String priceSpecificationRef) {
        this.priceSpecificationRef = priceSpecificationRef;
    }

    public String getPriceSpecificationRef() {
        return priceSpecificationRef;
    }

    public void setRateQuantity(String rateQuantity) {
        this.rateQuantity = rateQuantity;
    }

    public String getRateQuantity() {
        return rateQuantity;
    }

    public void setRatingsType(String ratingsType) {
        this.ratingsType = ratingsType;
    }

    public String getRatingsType() {
        return ratingsType;
    }

    public void setRcp(String rcp) {
        this.rcp = rcp;
    }

    public String getRcp() {
        return rcp;
    }

    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }

    public Double getSubTotal() {
        return subTotal;
    }

}
