
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.*;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Set;


/**
 * Routing details
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Routing)
public class Routing
    extends LogisticsObject
    implements Serializable
{

    /**
     * Locations of excluded Via Points
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_excludedViaPoints)
    @JsonProperty(Vocabulary.s_p_excludedViaPoints)
    protected Set<Location> excludedViaPoints;
    /**
     * Reference to the BookingOptionRequest the information of the LogisticsObject is detailling
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forBookingOptionRequest)
    @JsonProperty(Vocabulary.s_p_forBookingOptionRequest)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingOptionRequest forBookingOptionRequest;
    /**
     * Reference to the BookingOptionRequest the LogisticsObject is detailling
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forBookingOptions)
    @JsonProperty(Vocabulary.s_p_forBookingOptions)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingOption forBookingOptions;
    /**
     * Scheduled Legs class to be used to identify legs. Can be used with Booking Option Request as an indicator of preferred Routing or with Booking Option when a carrier proposes a specific Routing.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_scheduledLegs)
    @JsonProperty(Vocabulary.s_p_scheduledLegs)
    protected Set<ScheduledLegs> scheduledLegs;
    /**
     * Aircraft possibility code - Refers to CXML Code List 1.46 that contains values such as "Pure freighter flight carrying Loose Load Cargo - BBF"
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_aircraftPossibilityCode)
    @JsonProperty(Vocabulary.s_p_aircraftPossibilityCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String aircraftPossibilityCode;
    /**
     * Latest Arrival date time (requested or proposed)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_latestArrivalDateTime)
    @JsonProperty(Vocabulary.s_p_latestArrivalDateTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime latestArrivalDateTime;
    /**
     * Maximum number of connections of the transport movement (requested or proposed)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_maxConnections)
    @JsonProperty(Vocabulary.s_p_maxConnections)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer maxConnections;
    /**
     * Indicates interlining (requested or proposed)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_onlineInd)
    @JsonProperty(Vocabulary.s_p_onlineInd)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean onlineInd;
    /**
     * Indicates if RFS (Road Feeder Services) is included (requested or proposed)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_rfsInd)
    @JsonProperty(Vocabulary.s_p_rfsInd)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean rfsInd;

    public void setExcludedViaPoints(Set<Location> excludedViaPoints) {
        this.excludedViaPoints = excludedViaPoints;
    }

    public Set<Location> getExcludedViaPoints() {
        return excludedViaPoints;
    }

    public void setForBookingOptionRequest(BookingOptionRequest forBookingOptionRequest) {
        this.forBookingOptionRequest = forBookingOptionRequest;
    }

    public BookingOptionRequest getForBookingOptionRequest() {
        return forBookingOptionRequest;
    }

    public void setForBookingOptions(BookingOption forBookingOptions) {
        this.forBookingOptions = forBookingOptions;
    }

    public BookingOption getForBookingOptions() {
        return forBookingOptions;
    }

    public void setScheduledLegs(Set<ScheduledLegs> scheduledLegs) {
        this.scheduledLegs = scheduledLegs;
    }

    public Set<ScheduledLegs> getScheduledLegs() {
        return scheduledLegs;
    }

    public void setAircraftPossibilityCode(String aircraftPossibilityCode) {
        this.aircraftPossibilityCode = aircraftPossibilityCode;
    }

    public String getAircraftPossibilityCode() {
        return aircraftPossibilityCode;
    }

    public void setLatestArrivalDateTime(OffsetDateTime latestArrivalDateTime) {
        this.latestArrivalDateTime = latestArrivalDateTime;
    }

    public OffsetDateTime getLatestArrivalDateTime() {
        return latestArrivalDateTime;
    }

    public void setMaxConnections(Integer maxConnections) {
        this.maxConnections = maxConnections;
    }

    public Integer getMaxConnections() {
        return maxConnections;
    }

    public void setOnlineInd(Boolean onlineInd) {
        this.onlineInd = onlineInd;
    }

    public Boolean getOnlineInd() {
        return onlineInd;
    }

    public void setRfsInd(Boolean rfsInd) {
        this.rfsInd = rfsInd;
    }

    public Boolean getRfsInd() {
        return rfsInd;
    }

}
