
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import org.iata.cargo.Vocabulary;


/**
 * Security status details
 * 
 * This class was generated by OWL2Java 0.13.3
 * 
 */
@OWLClass(iri = Vocabulary.s_c_SecurityStatus)
public class SecurityStatus
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Name of person (or employee ID) and Regulated entity identifier (e.g. Regulated Agent Identifier) is mandatory
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_issuedBy_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, min = 1, max = -1)
    })
    protected Set<Company> issuedBy;
    /**
     * Date and time when the security status was issued
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_issuedOn)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", min = 1, max = -1)
    })
    protected Set<Date> issuedOn;
    /**
     * Party type - e.g. RA - Regulated Agent, KC - Known Consignor, AO - Aircraft Operator, RC - Regulated Carrier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_regulatedPartyType_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", min = 1, max = -1)
    })
    protected Set<String> regulatedPartyType;
    /**
     * Security status indicator - e.g. SPX- Cargo Secure for Passenger and All-Cargo Aircraft 
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_statusCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", min = 1, max = -1)
    })
    protected Set<String> statusCode;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("SecurityStatus {"+ name)+"<")+ id)+">")+"}");
    }

    public void setIssuedBy(Set<Company> issuedBy) {
        this.issuedBy = issuedBy;
    }

    public Set<Company> getIssuedBy() {
        return issuedBy;
    }

    public void setIssuedOn(Set<Date> issuedOn) {
        this.issuedOn = issuedOn;
    }

    public Set<Date> getIssuedOn() {
        return issuedOn;
    }

    public void setRegulatedPartyType(Set<String> regulatedPartyType) {
        this.regulatedPartyType = regulatedPartyType;
    }

    public Set<String> getRegulatedPartyType() {
        return regulatedPartyType;
    }

    public void setStatusCode(Set<String> statusCode) {
        this.statusCode = statusCode;
    }

    public Set<String> getStatusCode() {
        return statusCode;
    }

}
