
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Types;
import io.swagger.annotations.ApiModelProperty;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Service request details
 * 
 * This class was generated by OWL2Java 0.15.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ServiceRequest)
public class ServiceRequest
    extends LogisticsObject
    implements Serializable
{

    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_ServiceRequest)
    protected Set<String> types;

    /**
     * Service request code
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_code_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_code_A)
    protected String code;
    /**
     * Service request description
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_serviceRequestDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_serviceRequestDescription)
    protected String serviceRequestDescription;
    /**
     * Service request statement text
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_statementText)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_statementText)
    protected String statementText;
    /**
     * Service request statement type - e.g. Dangerous Goods, Lithium Ion Battery, Live Animal Certificate
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_statementType)
    @JsonProperty(Vocabulary.s_p_statementType)
    protected Set<String> statementType;

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setServiceRequestDescription(String serviceRequestDescription) {
        this.serviceRequestDescription = serviceRequestDescription;
    }

    public String getServiceRequestDescription() {
        return serviceRequestDescription;
    }

    public void setStatementText(String statementText) {
        this.statementText = statementText;
    }

    public String getStatementText() {
        return statementText;
    }

    public void setStatementType(Set<String> statementType) {
        this.statementType = statementType;
    }

    public Set<String> getStatementType() {
        return statementType;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

}
