
package org.iata.cargo.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.iata.cargo.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Activity to describe transports, replaces the TransportSegment in v1.1 and above
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TransportMovement)
public class TransportMovement
    extends LogisticsActivity
    implements Serializable
{

    /**
     * Reference to the arrival Location
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasArrivalLocation)
@JsonProperty(Vocabulary.s_p_hasArrivalLocation)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Location, max = 1)
    })
    protected Set<Thing> hasArrivalLocation;
    /**
     * Information about the calculated distance
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasCalculatedDistance)
@JsonProperty(Vocabulary.s_p_hasCalculatedDistance)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Value, max = 1)
    })
    protected Set<Thing> hasCalculatedDistance;
    /**
     * Information about the calculated fuel amount
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasCalculatedFuelAmount)
@JsonProperty(Vocabulary.s_p_hasCalculatedFuelAmount)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Value, max = 1)
    })
    protected Set<Thing> hasCalculatedFuelAmount;
    /**
     * References to CO2Emissions
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasCo2Emissions)
@JsonProperty(Vocabulary.s_p_hasCo2Emissions)
    protected Set<CO2Emissions> hasCo2Emissions;
    /**
     * Reference to the depature Location
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasDepartureLocation)
@JsonProperty(Vocabulary.s_p_hasDepartureLocation)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Location, max = 1)
    })
    protected Set<Thing> hasDepartureLocation;
    /**
     * References to all Actions performed for the TransportMovement
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasLogisticsAction)
@JsonProperty(Vocabulary.s_p_hasLogisticsAction)
    protected Set<LogisticsAction> hasLogisticsAction;
    /**
     * Information about the measured distance
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasMeasuredDistance)
@JsonProperty(Vocabulary.s_p_hasMeasuredDistance)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Value, max = 1)
    })
    protected Set<Thing> hasMeasuredDistance;
    /**
     * Information about the measured fuel amount
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasMeasuredFuelAmount)
@JsonProperty(Vocabulary.s_p_hasMeasuredFuelAmount)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Value, max = 1)
    })
    protected Value hasMeasuredFuelAmount;
    /**
     * Reference to the TransportMeans operating the TransportMovement
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_isOperatedByTransportMeans)
@JsonProperty(Vocabulary.s_p_isOperatedByTransportMeans)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_TransportMeans, max = 1)
    })
    protected TransportMeans isOperatedByTransportMeans;
    /**
     * e.g. Kerosene, Diesel, SAF, Electricity [renewable], Electricity [non-renewable]
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasFuelType)
@JsonProperty(Vocabulary.s_p_hasFuelType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasFuelType;
    /**
     * Mode of transport code, refer to UNECE Rec. 19 https://unece.org/fileadmin/DAM/cefact/recommendations/rec19/rec19_01cf19e.pdf
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasModeCode)
@JsonProperty(Vocabulary.s_p_hasModeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasModeCode;
    /**
     * Pre-Carriage, Main-Carriage or On-Carriage
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasModeQualifier)
@JsonProperty(Vocabulary.s_p_hasModeQualifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasModeQualifier;
    /**
     * Seal identifier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSeal)
@JsonProperty(Vocabulary.s_p_hasSeal)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasSeal;
    /**
     * Airline flight number, or rail/truck/maritime line id
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasTransportIdentifier)
@JsonProperty(Vocabulary.s_p_hasTransportIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", max = 1)
    })
    protected Set<String> hasTransportIdentifier;

    public void setHasArrivalLocation(Set<Thing> hasArrivalLocation) {
        this.hasArrivalLocation = hasArrivalLocation;
    }

    public Set<Thing> getHasArrivalLocation() {
        return hasArrivalLocation;
    }

    public void setHasCalculatedDistance(Set<Thing> hasCalculatedDistance) {
        this.hasCalculatedDistance = hasCalculatedDistance;
    }

    public Set<Thing> getHasCalculatedDistance() {
        return hasCalculatedDistance;
    }

    public void setHasCalculatedFuelAmount(Set<Thing> hasCalculatedFuelAmount) {
        this.hasCalculatedFuelAmount = hasCalculatedFuelAmount;
    }

    public Set<Thing> getHasCalculatedFuelAmount() {
        return hasCalculatedFuelAmount;
    }

    public void setHasCo2Emissions(Set<CO2Emissions> hasCo2Emissions) {
        this.hasCo2Emissions = hasCo2Emissions;
    }

    public Set<CO2Emissions> getHasCo2Emissions() {
        return hasCo2Emissions;
    }

    public void setHasDepartureLocation(Set<Thing> hasDepartureLocation) {
        this.hasDepartureLocation = hasDepartureLocation;
    }

    public Set<Thing> getHasDepartureLocation() {
        return hasDepartureLocation;
    }

    public void setHasLogisticsAction(Set<LogisticsAction> hasLogisticsAction) {
        this.hasLogisticsAction = hasLogisticsAction;
    }

    public Set<LogisticsAction> getHasLogisticsAction() {
        return hasLogisticsAction;
    }

    public void setHasMeasuredDistance(Set<Thing> hasMeasuredDistance) {
        this.hasMeasuredDistance = hasMeasuredDistance;
    }

    public Set<Thing> getHasMeasuredDistance() {
        return hasMeasuredDistance;
    }

    public void setHasMeasuredFuelAmount(Value hasMeasuredFuelAmount) {
        this.hasMeasuredFuelAmount = hasMeasuredFuelAmount;
    }

    public Value getHasMeasuredFuelAmount() {
        return hasMeasuredFuelAmount;
    }

    public void setIsOperatedByTransportMeans(TransportMeans isOperatedByTransportMeans) {
        this.isOperatedByTransportMeans = isOperatedByTransportMeans;
    }

    public TransportMeans getIsOperatedByTransportMeans() {
        return isOperatedByTransportMeans;
    }

    public void setHasFuelType(String hasFuelType) {
        this.hasFuelType = hasFuelType;
    }

    public String getHasFuelType() {
        return hasFuelType;
    }

    public void setHasModeCode(Set<String> hasModeCode) {
        this.hasModeCode = hasModeCode;
    }

    public Set<String> getHasModeCode() {
        return hasModeCode;
    }

    public void setHasModeQualifier(Set<String> hasModeQualifier) {
        this.hasModeQualifier = hasModeQualifier;
    }

    public Set<String> getHasModeQualifier() {
        return hasModeQualifier;
    }

    public void setHasSeal(String hasSeal) {
        this.hasSeal = hasSeal;
    }

    public String getHasSeal() {
        return hasSeal;
    }

    public void setHasTransportIdentifier(Set<String> hasTransportIdentifier) {
        this.hasTransportIdentifier = hasTransportIdentifier;
    }

    public Set<String> getHasTransportIdentifier() {
        return hasTransportIdentifier;
    }

}
