
package org.iata.cargo.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Types;
import io.swagger.annotations.ApiModelProperty;
import org.iata.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Unit Load Device details
 * 
 * This class was generated by OWL2Java 0.14.6
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ULD)
public class Uld
    extends LogisticsObject
    implements Serializable
{

    @Types
    @JsonProperty("@type")
    @ApiModelProperty(allowableValues = Vocabulary.s_c_ULD)
    protected Set<String> types;

    /**
     * Reference documents details 
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_externalReference_A_A_A)
    @JsonProperty(Vocabulary.s_p_externalReference_A_A_A)
    protected Set<ExternalReference> externalReference;
    /**
     * Owner company details and contacts for the ULD
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ownerCompany)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_ownerCompany)
    protected Company ownerCompany;
    /**
     * Tare weight of the empty ULD
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_tareWeight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_tareWeight)
    protected Value tareWeight;
    /**
     * Segment related to the ULD movement
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportSegment_A_A)
    @JsonProperty(Vocabulary.s_p_transportSegment_A_A)
    protected Set<TransportSegment> transportSegment;
    /**
     * Details of contained (virtual) piece(s)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_upid)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    @JsonProperty(Vocabulary.s_p_upid)
    protected Piece upid;
    /**
     * US / ATA Unit Load Device type code e.g. M2
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_ataDesignator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_ataDesignator)
    protected String ataDesignator;
    /**
     * ULD profile, dimensions & shape
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_contour)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_contour)
    protected String contour;
    /**
     * Position of the shipment in the aircraft - e.g. lower or main deck 
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_deckPosition)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_deckPosition)
    protected String deckPosition;
    /**
     * ULD height or loading limitation code. Refer CXML Code List 1.47,  e.g. R - ULD Height above 244 centimetres
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_loadingIndicator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_loadingIndicator)
    protected String loadingIndicator;
    /**
     * Owner code of the ULD in aa, an or na format - owner can be an airline or leasing company
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_ownerCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_ownerCode)
    protected String ownerCode;
    /**
     * Issuer of the ULD owner code 
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_ownerCodeIssuer)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_ownerCodeIssuer)
    protected String ownerCodeIssuer;
    /**
     * ULD serial number
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_serialNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_serialNumber)
    protected String serialNumber;
    /**
     * Standard Unit Load Device type code e.g. AKE - Certified Container - Contoured
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_uldType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty(Vocabulary.s_p_uldType)
    protected String uldType;

    public void setExternalReference(Set<ExternalReference> externalReference) {
        this.externalReference = externalReference;
    }

    public Set<ExternalReference> getExternalReference() {
        return externalReference;
    }

    public void setOwnerCompany(Company ownerCompany) {
        this.ownerCompany = ownerCompany;
    }

    public Company getOwnerCompany() {
        return ownerCompany;
    }

    public void setTareWeight(Value tareWeight) {
        this.tareWeight = tareWeight;
    }

    public Value getTareWeight() {
        return tareWeight;
    }

    public void setTransportSegment(Set<TransportSegment> transportSegment) {
        this.transportSegment = transportSegment;
    }

    public Set<TransportSegment> getTransportSegment() {
        return transportSegment;
    }

    public void setUpid(Piece upid) {
        this.upid = upid;
    }

    public Piece getUpid() {
        return upid;
    }

    public void setAtaDesignator(String ataDesignator) {
        this.ataDesignator = ataDesignator;
    }

    public String getAtaDesignator() {
        return ataDesignator;
    }

    public void setContour(String contour) {
        this.contour = contour;
    }

    public String getContour() {
        return contour;
    }

    public void setDeckPosition(String deckPosition) {
        this.deckPosition = deckPosition;
    }

    public String getDeckPosition() {
        return deckPosition;
    }

    public void setLoadingIndicator(String loadingIndicator) {
        this.loadingIndicator = loadingIndicator;
    }

    public String getLoadingIndicator() {
        return loadingIndicator;
    }

    public void setOwnerCode(String ownerCode) {
        this.ownerCode = ownerCode;
    }

    public String getOwnerCode() {
        return ownerCode;
    }

    public void setOwnerCodeIssuer(String ownerCodeIssuer) {
        this.ownerCodeIssuer = ownerCodeIssuer;
    }

    public String getOwnerCodeIssuer() {
        return ownerCodeIssuer;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setUldType(String uldType) {
        this.uldType = uldType;
    }

    public String getUldType() {
        return uldType;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

}
