package org.iata.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {
  @Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
        .select()
        .apis(RequestHandlerSelectors.basePackage("org.iata.resource"))
        .paths(PathSelectors.any())
        .build()
        .apiInfo(apiEndPointsInfo());
  }

  private ApiInfo apiEndPointsInfo() {
    return new ApiInfoBuilder()
        .title("ONE Record API Documentation")
        .description("ONE Record Server autogenerated Swagger API documentation. " +
            " <br> " +
            "Note! By testing this API documentation you agree the data and actions that you " +
            "submit and perform in this sandbox are entirely at your own responsibility. We recommend that you do not introduce private, commercial or other sensitive information in this sandbox since its exposure cannot be guaranteed. IATA is not liable for your actions or data. " +
            " <br> More information about ONE Record specifications on [IATA Github repository](https://github.com/IATA-Cargo/ONE-Record) and " +
            "on the [ONE Record Developer Portal](https://onerecord.iata.org). <br>")
        .contact(new Contact("IATA ONE Record", "https://www.iata.org/whatwedo/cargo/e/Pages/one-record.aspx", "onerecord@iata.org"))
        .license("MIT License")
        .licenseUrl("https://opensource.org/licenses/MIT")
        .version("1.1")
        .build();
  }

}