
package org.iata.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import io.swagger.v3.oas.annotations.media.Schema;
import org.iata.api.Vocabulary;

import java.io.Serializable;


/**
 * Delegation Request to 3rd parties
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_AccessDelegationRequest)
@Schema(
        type = "object",
        title = "AccessDelegationRequest",
        allOf = {
                ActionRequest.class
        }
)
public class AccessDelegationRequest
    extends ActionRequest
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_hasAccessDelegation)
    @JsonProperty(Vocabulary.s_p_hasAccessDelegation)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_AccessDelegation, min = 1, max = 1)
    })
    protected AccessDelegation hasAccessDelegation;

    public void setHasAccessDelegation(AccessDelegation hasAccessDelegation) {
        this.hasAccessDelegation = hasAccessDelegation;
    }

    public AccessDelegation getHasAccessDelegation() {
        return hasAccessDelegation;
    }

}
