
package org.iata.api.model;

import java.io.Serializable;
import java.net.URI;
import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import org.iata.api.Vocabulary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.iata.cargo.model.Organization;


/**
 * Information about the ONE Record server in the Internet of Logistics
 * 
 * This class was generated by OWL2Java 0.20.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ServerInformation)
public class ServerInformation
    implements Serializable
{

    @Id(generated = true)
@JsonProperty("@id")
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
@JsonIgnore
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
@JsonIgnore
    protected String description;
    @Types
@JsonProperty("@type")
    protected Set<String> types;
    @Properties
@JsonIgnore
    protected Map<String, Set<String>> properties;
    /**
     * The data owner of the servers data.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasDataOwner)
@JsonProperty(Vocabulary.s_p_hasDataOwner)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Organization, min = 1, max = 1)
    })
    protected Organization hasDataOwner;
    /**
     * ONE Record API endpoint in the Internet of Logistics
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasServerEndpoint)
@JsonProperty(Vocabulary.s_p_hasServerEndpoint)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", min = 1, max = 1)
    })
    protected Set<String> hasServerEndpoint;
    /**
     * Supported ONE Record API versions by the server, MUST include at least one supported version.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSupportedApiVersion)
@JsonProperty(Vocabulary.s_p_hasSupportedApiVersion)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", min = 1, max = -1)
    })
    protected Set<String> hasSupportedApiVersion;
    /**
     * Supported content types of the server, MUST contain at least application/ld+json
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSupportedContentType)
@JsonProperty(Vocabulary.s_p_hasSupportedContentType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", min = 1, max = -1)
    })
    protected Set<String> hasSupportedContentType;
    /**
     * Optional list of supported encodings of the ONE Record server, e.g. gzip
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSupportedEncoding)
@JsonProperty(Vocabulary.s_p_hasSupportedEncoding)
    protected Set<String> hasSupportedEncoding;
    /**
     * Supported languages of the ONE Record API, minimum is en-US (American English)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSupportedLanguage)
@JsonProperty(Vocabulary.s_p_hasSupportedLanguage)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", min = 1, max = -1)
    })
    protected Set<String> hasSupportedLanguage;
    /**
     * Supported logistics object types on the server
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSupportedLogisticsObjectType)
@JsonProperty(Vocabulary.s_p_hasSupportedLogisticsObjectType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#anyURI", min = 1, max = -1)
    })
    protected Set<URI> hasSupportedLogisticsObjectType;
    /**
     * Supported ontologies on the server, MUST be versioned IRIs
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasSupportedOntology)
@JsonProperty(Vocabulary.s_p_hasSupportedOntology)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#anyURI", min = 1, max = -1)
    })
    protected Set<URI> hasSupportedOntology;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("ServerInformation {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasDataOwner(Organization hasDataOwner) {
        this.hasDataOwner = hasDataOwner;
    }

    public Organization getHasDataOwner() {
        return hasDataOwner;
    }

    public void setHasServerEndpoint(Set<String> hasServerEndpoint) {
        this.hasServerEndpoint = hasServerEndpoint;
    }

    public Set<String> getHasServerEndpoint() {
        return hasServerEndpoint;
    }

    public void setHasSupportedApiVersion(Set<String> hasSupportedApiVersion) {
        this.hasSupportedApiVersion = hasSupportedApiVersion;
    }

    public Set<String> getHasSupportedApiVersion() {
        return hasSupportedApiVersion;
    }

    public void setHasSupportedContentType(Set<String> hasSupportedContentType) {
        this.hasSupportedContentType = hasSupportedContentType;
    }

    public Set<String> getHasSupportedContentType() {
        return hasSupportedContentType;
    }

    public void setHasSupportedEncoding(Set<String> hasSupportedEncoding) {
        this.hasSupportedEncoding = hasSupportedEncoding;
    }

    public Set<String> getHasSupportedEncoding() {
        return hasSupportedEncoding;
    }

    public void setHasSupportedLanguage(Set<String> hasSupportedLanguage) {
        this.hasSupportedLanguage = hasSupportedLanguage;
    }

    public Set<String> getHasSupportedLanguage() {
        return hasSupportedLanguage;
    }

    public void setHasSupportedLogisticsObjectType(Set<URI> hasSupportedLogisticsObjectType) {
        this.hasSupportedLogisticsObjectType = hasSupportedLogisticsObjectType;
    }

    public Set<URI> getHasSupportedLogisticsObjectType() {
        return hasSupportedLogisticsObjectType;
    }

    public void setHasSupportedOntology(Set<URI> hasSupportedOntology) {
        this.hasSupportedOntology = hasSupportedOntology;
    }

    public Set<URI> getHasSupportedOntology() {
        return hasSupportedOntology;
    }

}
