
package org.iata.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import io.swagger.v3.oas.annotations.media.Schema;
import org.iata.api.Vocabulary;

import java.io.Serializable;


/**
 * SubscriptionRequest initiated by subscribers to publisher (data owner) for themselves or for a third party subscriber.
 * 
 * This class was generated by OWL2Java 0.22.0
 * 
 */
@OWLClass(iri = Vocabulary.s_c_SubscriptionRequest)
@Schema(
        type = "object",
        title = "SubscriptionRequest",
        allOf = {
                ActionRequest.class
        }
)
public class SubscriptionRequest
    extends ActionRequest
    implements Serializable
{

    /**
     * Link to the requestors Subscription object with all subscription information
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasSubscription)
    @JsonProperty(Vocabulary.s_p_hasSubscription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Subscription, min = 1, max = 1)
    })
    protected Subscription hasSubscription;

    public void setHasSubscription(Subscription hasSubscription) {
        this.hasSubscription = hasSubscription;
    }

    public Subscription getHasSubscription() {
        return hasSubscription;
    }

}
